### ISSUE TITLE
Can we use more images instead just single image?

### ISSUE THREAD

**Issue by SanketDhuri** [NeuralCarver/Michelangelo#7]
Can we use more images instead just single image to get the 3d mesh more accurate i.e. Multiview image captured different viewpoints of same object like left-right and top bottom

**Comment by Maikouuu** [comment]
Thanks for the interesting idea. For image-conditioned generation, as the number of input images increases, the model may be capable of outputting more accurate shapes. Incorporating additional geometry assumptions could make it easier to achieve this capability. However, this would require additional design and training for the model, which Michelangelo currently does not possess. Moreover, since Michelangelo is a generative model, it can only present plausible results (similar to the conditioning input) rather than reconstructions (faithfully conforms to the real geometry of conditioning input).

**Comment by SanketDhuri** [comment]
Do you know any such model which does such task efficiently?

**Comment by Maikouuu** [comment]
I apologize for not being able to provide you with specific advice, as I am not an expert in sparse-view reconstruction. 
However, you may search for recent top conference papers or GitHub using keywords such as "sparse-view reconstruction" to find the latest research and techniques in this area.
